import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
 
const outfit = Outfit({
   subsets: ["latin"],
});
 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="bg-white" lang="en">
       
      <body
        className={`antialiased`}>
          <nav>
        <Navbar></Navbar>
      </nav>
        {children}
        <footer className="light bg-white">
<Footer></Footer>
        </footer>  
      </body>
         </html>
  );
}
